# Generated by Django 5.0.4 on 2024-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('count', models.CharField(max_length=300, verbose_name='تعداد محصول')),
                ('is_active', models.BooleanField(verbose_name='موجودی')),
            ],
        ),
    ]
